### ISSUE TITLE
openEHR-TEST_PKG-ENTRY_WRONG.rm_type_wrong.v1.0.0.adls needs .0.0 after id

### ISSUE THREAD

**Issue by pieterbos** [openEHR/adl-archetypes#7]

**Comment by pieterbos** [comment]
also uses at0000 instead of id1 as root id code

**Comment by pieterbos** [comment]
also its still adl 1.5. that explains the id code and version, but still a problem if it's in the adl2-reference package

also concept instead of language

**Comment by pieterbos** [comment]
i'll just make a pull request with changes soon.

**Comment by wolandscat** [comment]
Corrected.
